agent {
  data_dir = "/tmp/spire-agent"
  log_level = "DEBUG"
  server_address = "spire-server"
  server_port = "8081"
  socket_path = "/run/spire/sockets/agent.sock"
  trust_bundle_path = "/openbao/tls/ca.crt"
  trust_domain = "example.org"
  join_token = "__JOIN_TOKEN__"
}

plugins {
  NodeAttestor "join_token" {
    plugin_data {}
  }

  KeyManager "memory" {
    plugin_data {}
  }

  WorkloadAttestor "unix" {
    plugin_data {
      discover_workload_path = false
    }
  }
}
