server {
  bind_address = "0.0.0.0"
  bind_port = "8081"
  trust_domain = "example.org"
  data_dir = "/tmp/spire-server"
  log_level = "DEBUG"
  ca_key_type = "rsa-2048"
  ca_ttl = "24h"
  default_x509_svid_ttl = "1h"
  default_jwt_svid_ttl = "1h"
  jwt_issuer = "https://example.org"
}

plugins {
  DataStore "sql" {
    plugin_data {
      database_type = "sqlite3"
      connection_string = "file:spiremem?mode=memory&cache=shared"
    }
  }

  NodeAttestor "join_token" {
    plugin_data {}
  }

  KeyManager "memory" {
    plugin_data {}
  }

  UpstreamAuthority "vault" {
    plugin_data {
      vault_addr           = "https://openbao-transit:8200"
      pki_mount_point      = "pki"
      ca_cert_path         = "/openbao/tls/ca.crt"
      insecure_skip_verify = false
      cert_auth {
        cert_auth_mount_point = "cert"
        client_cert_path      = "/openbao/tls/spire-client.crt"
        client_key_path       = "/openbao/tls/spire-client.key"
      }
    }
  }
}
